# Use the latest LTS version of Node.js
FROM node:22.14-alpine
 
# Set the working directory inside the container
WORKDIR /app
 
# Copy build dir
COPY . /app/
 
# Install dependencies
RUN npm install --only=prod

 
# Expose the port your app runs on
EXPOSE 3000
 
# Define the command to run your app
CMD ["node", "index.js"]